### ISSUE TITLE
mod框架next无法安装。非stream版，显示错误：next 0.44 与 BepInEx版本不匹配

### ISSUE THREAD

**Issue by zhitianjiao2012** [magicskysword/Next#10]
求助mod框架next无法安装，BepInEx用的是 BepInEx_x86_5.4.5.0.zip 。

非stream版，显示错误：next 0.44 与 BepInEx版本不匹配：

——不放Next则正常，安装 放入Next则报错—— 反复切换了Next 0.1~Next0.44没有一个适配的，无法安装。
--------------------------- 调整BepInEx的配置文件，让显示控制台日志后，显示如下日志：---------------------------
[Warning:   BepInEx] Plugin [Next 0.4.1] targets a wrong version of BepInEx (5.4.18.0) and might not work until you update
[Info   :   BepInEx] Loading [Next 0.4.1]
[Info   :      Next] 开始加载xlua.dll
[Info   :      Next] 加载完毕
[Error  : Unity Log] DllNotFoundException: xlua
--------------------------

（放入Next 报错）
（不放 不安装Next，则不报错）

**Comment by magicskysword** [comment]
请确保你的Next文件直接放在Plugins文件夹下（而不是子文件夹），文件地址如下：
觅长生\BepInEx\plugins\Next.dll
觅长生\BepInEx\plugins\NextConfig
觅长生\BepInEx\plugins\NextLib
文件位置不正确将导致无法读取对应库文件与配置文件

**Comment by zhitianjiao2012** [comment]
> 
谢谢您的答复！我已经一直将 文件放在对应的位置：**仍然报错，相同错误。不知是否Next不匹配**

觅长生\BepInEx\plugins\Next.dll    其他2个文件夹NextConfig、NextLib 也是放在同一个目录下。

路径：
G:\michangsheng\觅长生\BepInEx\plugins 
├─NextConfig
│  └─language
└─NextLib
    └─Lua
        ├─libs
        ├─perf
        ├─tdr
        └─xlua



----------------------------------- 仍然报错，相同错误。不知是否Next不匹配 --------------------
[Message:   BepInEx] BepInEx 5.4.5.0 - 觅长生test
[Info   :   BepInEx] Running under Unity v2018.3.11.5268257
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
**[Warning:   BepInEx] Plugin [Next 0.4.4] targets a wrong version of BepInEx (5.4.17.0) and might not work until you update**
[Info   :   BepInEx] Loading [Next 0.4.4]
[Info   :      Next] 开始加载xlua.dll
[Info   :      Next] 加载完毕
**[Error  : Unity Log] DllNotFoundException: xlua**
Stack trace:
XLua.LuaEnv..ctor () (at <9783909c4d574780ba07cae1d8e77646>:0)
SkySwordKill.Next.Lua.LuaManager.InitLuaEnv () (at <9783909c4d574780ba07cae1d8e77646>:0)
SkySwordKill.Next.Lua.LuaManager..ctor () (at <9783909c4d574780ba07cae1d8e77646>:0)
SkySwordKill.Next.Main.Init () (at <9783909c4d574780ba07cae1d8e77646>:0)
SkySwordKill.Next.Main.Awake () (at <9783909c4d574780ba07cae1d8e77646>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] clientapp::start()
------------------------------------------------------------------------------

**Comment by magicskysword** [comment]
在NextLib文件夹中是否有Microsoft.CSharp.dll与xlua.dll？
Next的剧情解析依赖于这两个dll

**Comment by zhitianjiao2012** [comment]
在NextLib文件夹中 有的：2个文件、1个文件夹

/Lua
Microsoft.CSharp.dll
xlua.dll

**Comment by magicskysword** [comment]
这种情况有点奇怪......你方便加群发一下具体的信息吗？群号：103246254 《觅长生》3DM交流群

**Comment by zhitianjiao2012** [comment]
https://bbs.3dmgame.com/forum.php?mod=viewthread&tid=6298398

**Comment by magicskysword** [comment]
看到了，你使用的BepinEx版本不对（小版本过老，且使用的是x86版本），你在Steam上觅长生右键 - 验证完整性，觅长生自己已经内置一个BepInEx（64位的）
因为Next加载的xlua是x64的native dll，所以使用32位版本加载会产生异常

**Comment by zhitianjiao2012** [comment]
好的！谢谢

**Comment by magicskysword** [comment]
[Message:   BepInEx] BepInEx 5.4.17.0 - 觅长生 (2021/11/5 22:18:19)
[Info   :   BepInEx] Running under Unity v2018.4.36.16660467
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.17.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] BepInEx is about load the following assemblies:
UnityEngine.CoreModule.dll
[Info   :   BepInEx] The assemblies were dumped into D:\soft\steam\steamapps\common\觅长生\BepInEx\DumpedAssemblies\觅长生
[Info   :   BepInEx] Load any assemblies into the debugger, set breakpoints and continue execution.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 7 plugins to load
[Warning:   BepInEx] Plugin [ResourcesPatch 1.0.0] targets a wrong version of BepInEx (5.4.18.0) and might not work until you update
[Info   :   BepInEx] Loading [Configuration Manager 16.1]
[Info   :   BepInEx] Loading [UnityExplorer 4.5.0]
[Message:UnityExplorer] UnityExplorer 4.5.0 initializing...
[Message:UnityExplorer] Cached AppDomain assemblies in 0.7495782 seconds
[Message:UnityExplorer] Finished UniverseLib initial setup
[Info   :   BepInEx] Loading [宵夜修改器 1.3.0]
[Info   :   BepInEx] Loading [Next 0.4.4]
[Info   :      Next] 开始加载xlua.dll
[Info   :      Next] 加载完毕

**Comment by magicskysword** [comment]
最新版本的BepinEx输出如上

**Comment by zhitianjiao2012** [comment]
明白 问题所在 了！真的非常感谢大佬
