### ISSUE TITLE
Next框架UI问题

### ISSUE THREAD

**Issue by lazape** [magicskysword/Next#12]
版本：0.6.4
问题：使用时会出现UI问题，具体表现在显示item列表的框会黑屏，尤其进入物品编辑查看功法书的时候。同时黑屏时无法重新编辑MOD，只有重启游戏这一条路

**Comment by 2717753650** [comment]
版本：0.7.3
问题：连续使用startfight指令进行战斗结束的事件跳转时无法正确触发，当第一次战斗胜利后，第二次的战斗在开始时默认胜利，直接触发第二次战斗胜利后的事件，并且由于开始战斗后覆盖掉了第二次战斗时候的对话事件，使得后续事件触发失败。

**Comment by magicskysword** [comment]
UI问题无法重现，连续战斗问题已记录，新开了一个Issue。
