### ISSUE TITLE
大佬，steam deck上的steam os系统加载不出来Next框架

### ISSUE THREAD

**Issue by yinnengzhong** [magicskysword/Next#13]
打了前置mod，但是右上角没有显示出next，其它的mod也不生效。

**Comment by magicskysword** [comment]
我没有steamdeck，没法进行排查。
不过从你的描述里可以得知，这应该是BepInEx在steamdeck上运行异常的缘故，该帖子或许有所帮助：https://www.reddit.com/r/SteamDeck/comments/whwgkp/anyone_got_bepinex_to_work/

**Comment by yinnengzhong** [comment]
> 我没有steamdeck，没法进行排查。 不过从你的描述里可以得知，这应该是BepInEx在steamdeck上运行异常的缘故，该帖子或许有所帮助：https://www.reddit.com/r/SteamDeck/comments/whwgkp/anyone_got_bepinex_to_work/

感谢，解决了，在启动选项里面添加WINEDLLOVERRIDES="winhttp.dll=n,b" %command%就行了
