### ISSUE TITLE
冗余的HarmonyPatch补丁导致的资源加载存在不合理

### ISSUE THREAD

**Issue by TierneyJohn** [magicskysword/Next#17]
在处理Assets图片资源加载时，我看到Next中已经对原版的 ResManager 进行了补丁操作。在调用 "LoadSprite" 以及 "LoadTexture2D" 方法时提供了额外的资源插入操作。那么本质上就不再需要对其他的图片资源加载进行补丁操作了。

但实际上，我发现 Next 之中还是保留有其他时期的资源加载处理的，这本身并没有太大影响，至少对于使用Next编辑器提供的资源加载操作是没有额外影响的。

但实际上我今天在进行自己的Mod制作时，因为特殊需求所有需要自己处理图片资源加载。而我的做法也是直接对 ResManager 中的两个方法进行了额外的处理。这在其他的场景下都是可以正常获取到资源的，但是在进入**战斗场景**时，我发现战斗面板上的**技能图标显示异常**。

后续我进行了反复的排查发现，Next中的 SkillIconPatch 中对战斗时的 Skill初始化进行了额外的 patch，使得本来能够通过 ResManager.inst.LoadSprite 加载到的图片数据，因为 Postfix 方法被重新处理了。

![O O)6A3`17$LF8L$6LSUNPB](https://github.com/magicskysword/Next/assets/57483200/3048d13c-c812-4121-bb2a-9e33993adf09)

Postfix 方法的处理逻辑导致，图片资源会尝试在Next的资源管理中获取数据，如若未获取到对应的资源，则直接加载原版数据，而且是直接通过Resources进行的资源加载。这样的处理方式会使得其他Mod想要进行“特殊的资源加载”变得十分困难。

因此，在这里提出 Issue 希望能将原版资源的加载逻辑进行适当的变动，恢复原版的资源加载方式（如上图）。

另外，为了保险起见我这里也进行了额外的测试，直接拦截了这部分的数据处理逻辑，具体操作如下

![CG_7L `20X}FDIJ~@L3%MEO](https://github.com/magicskysword/Next/assets/57483200/d69dfcb7-f872-4efc-bf1a-47a386802860)
![C(CGIJY2)}8K{3VU390N0_3](https://github.com/magicskysword/Next/assets/57483200/74adf55a-22b5-42b2-b7f6-9d95a2d5b0a9)

而在游戏的实际测试中，我发现直接拦截也不会导致图标加载出现问题（因为本质上已经在 ResManager 中进行过处理了）

![744G_A2SG{R){33O_ 66}%R](https://github.com/magicskysword/Next/assets/57483200/04c5b52c-b3e6-4d21-aafa-b5ea3f6f885f)

所以，是否移除这部分额外的资源加载逻辑也是可行的呢？

涉及到的代码文件如下：
[ResManagerLoadSpritePatch](https://github.com/magicskysword/Next/blob/main/Next/Scr/Core/Patch/ResManagerLoadSpritePatch.cs)
[ResManagerLoadTexturePatch](https://github.com/magicskysword/Next/blob/main/Next/Scr/Core/Patch/ResManagerLoadTexturePatch.cs)
[SkillIconPatch](https://github.com/magicskysword/Next/blob/main/Next/Scr/Core/Patch/SkillIconPatch.cs)

**Comment by magicskysword** [comment]
改动很好，但是我Next代码有一部分代码丢家里了，还没上传，得等我暑假回去才能合并修复。

**Comment by magicskysword** [comment]
Patch代码不能去除，因为官方的加载逻辑尚未判断icon与skillId不同时的逻辑，而是统一加载skillId作为iconId，不过目前这部分代码已经修改为使用ResManager加载图标。
