### ISSUE TITLE
mod设置中的文本输入框宽度是0

### ISSUE THREAD

**Issue by Fengzi2333** [magicskysword/Next#3]

**Comment by magicskysword** [comment]
请问是哪个文本框，据测试剧情ID输入框与剧情指令调试框宽度是正常的

**Comment by Fengzi2333** [comment]
抱歉，我好像把next和BepInEx搞混了
这应该是BepInEx

**Comment by Fengzi2333** [comment]
抱歉再次打扰，麻烦你看一下[https://bbs.3dmgame.com/forum.php?mod=redirect&goto=findpost&ptid=6207429&pid=288675963](帖子的2437楼)这里，我现在有些不确定游戏内的参数配置是next实现的还是BepInEx自带的，因为我移除next相关文件后f1菜单也消失了

**Comment by magicskysword** [comment]
该配置参数调节窗口是由BepInEx的插件ConfigurationManager提供的，Next并未使用相关功能，仅使用了BepInEx内置的配置接口。相关Issue可以去这个库提 https://github.com/BepInEx/BepInEx.ConfigurationManager

**Comment by Fengzi2333** [comment]
> 该配置参数调节窗口是由BepInEx的插件ConfigurationManager提供的，Next并未使用相关功能，仅使用了BepInEx内置的配置接口。相关Issue可以去这个库提 https://github.com/BepInEx/BepInEx.ConfigurationManager

非常感谢
