### ISSUE TITLE
debug窗口与ConfigurationManager冲突

### ISSUE THREAD

**Issue by Fengzi2333** [magicskysword/Next#4]
next的debug菜单（默认f4呼出）与ConfigurationManager似乎存在冲突；当二者共存时，f4键无法呼出debug窗口，并且启动时debug窗口不弹出。

**Comment by magicskysword** [comment]
ConfigurationManager本身为独立窗口，捕获了其他输入，其打开时其他按键被捕获是正常特性。
Next从0.2.15版本已经修复了Debug窗口启动时弹出失灵的问题，请检查当前使用版本是否为最新版。

**Comment by Fengzi2333** [comment]
版本：0.2.15

**Comment by magicskysword** [comment]
问题无法复现
