### ISSUE TITLE
3.3版本红字报错，麻烦看看

### ISSUE THREAD

**Issue by fourteeth** [magicskysword/Next#7]
![报错](https://user-images.githubusercontent.com/32726958/153593409-aed06120-87d3-4ba2-94e9-1ded8f04089d.png)

红字提示见图片，麻烦作者大大看看

游戏已经验证过完整性和重装过 版本0.91120

**Comment by magicskysword** [comment]
0.3.3使用了测试版新版本的函数，导致该错误发生。
请等待稳定版更新，或将游戏切换为测试版，或使用0.3.2版本

**Comment by fourteeth** [comment]
牛了，我换回3.2 OK了，谢谢解惑。
